spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5432/websitedb
    username: postgres
    password: 01032002ama
    driver-class-name: org.postgresql.Driver



  jpa:
    hibernate:
      # PAY ATTENTION, BE CAUTIOUS!!!
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
